version: '3'

services:
  web:
    container_name: web
    image: photorec:latest
    restart: always
    build:
      context: ..
      dockerfile: devops/dockerfiles/prod-web
    ports:
      - "5000:8080"
    command: python run.py
