sudo: required

dist: xenial

# safelist
branches:
  only:
  - master
  - develop

language: python
python:
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

stages:
  - test
  - deploy-prod

jobs:
  include:
    - stage: test
      install: make travis-env
      script:
        - make test
        - make code-style
      after_success:
        - codecov

    - stage: deploy
      install: make travis-aws
      services:
        - docker
      script:
        - make docker-build
      after_success:
        - export PATH=$PATH:$HOME/.local/bin
        - eval $(aws ecr get-login --region us-east-2)
        - docker tag photorec:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/photorec:prod
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/photorec:prod
