sudo: required

dist: xenial

# safelist
branches:
  only:
  - master
  - develop

language: python
python:
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      install: make travis-env
      script:
        - make test
        - make code-style
      after_success:
        - codecov

    - stage: deploy
      install: make travis-env
      services:
        - docker
      script:
        - make aws-push-image
