dist: xenial

# safelist
branches:
  only:
  - master
  - develop

language: python
python:
  - "3.7"

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      install: make travis
      script:
        - make test
        - make code-style

    - stage: deploy
      script: echo Deploy
