dist: xenial

# safelist
branches:
  only:
  - master
  - develop

language: python
python:
  - "3.7"

# command to install dependencies
install: make travis
# # command to run tests
script: make test
