dist: xenial

# safelist
branches:
  only:
  - master
  - develop

language: python
python:
  - "3.7"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
install: make travis-setup
# # command to run tests
script: make test-run