version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: aws_localstack
    ports:
      - "4567-4584:4567-4584"
      - "9080:8080"
    environment:
      - SERVICES=s3,dynamodb
      - DEFAULT_REGION=us-west-2
      - DEBUG=1
